const contracted = {
    "ain't": "am not",
  "aren't": "are not",
  "can't": "cannot",
  "can't've": "cannot have",
  "'cause": "because",
  "could've": "could have",
  "couldn't": "could not",
  "couldn't've": "could not have",
  "didn't": "did not",
  "doesn't": "does not",
  "don't": "do not",
  "hadn't": "had not",
  "hadn't've": "had not have",
  "hasn't": "has not",
  "haven't": "have not",
  "he'd": "he would",
  "he'd've": "he would have",
  "he'll": "he will",
  "he'll've": "he will have",
  "he's": "he is",
  "how'd": "how did",
  "how'd'y": "how do you",
  "how'll": "how will",
  "how's": "how is",
  "I'd": "I would",
  "I'd've": "I would have",
  "I'll": "I will",
  "I'll've": "I will have",
  "I'm": "I am",
  "I've": "I have",
  "isn't": "is not",
  "it'd": "it had",
  "it'd've": "it would have",
  "it'll": "it will",
  "it'll've": "it will have",
  "it's": "it is",
  "let's": "let us",
  "ma'am": "madam",
  "mayn't": "may not",
  "might've": "might have",
  "mightn't": "might not",
  "mightn't've": "might not have",
  "must've": "must have",
  "mustn't": "must not",
  "mustn't've": "must not have",
  "needn't": "need not",
  "needn't've": "need not have",
  "o'clock": "of the clock",
  "oughtn't": "ought not",
  "oughtn't've": "ought not have",
  "shan't": "shall not",
  "sha'n't": "shall not",
  "shan't've": "shall not have",
  "she'd": "she would",
  "she'd've": "she would have",
  "she'll": "she will",
  "she'll've": "she will have",
  "she's": "she is",
  "should've": "should have",
  "shouldn't": "should not",
  "shouldn't've": "should not have",
  "so've": "so have",
  "so's": "so is",
  "that'd": "that would",
  "that'd've": "that would have",
  "that's": "that is",
  "there'd": "there had",
  "there'd've": "there would have",
  "there's": "there is",
  "they'd": "they would",
  "they'd've": "they would have",
  "they'll": "they will",
  "they'll've": "they will have",
  "they're": "they are",
  "they've": "they have",
  "to've": "to have",
  "wasn't": "was not",
  "we'd": "we had",
  "we'd've": "we would have",
  "we'll": "we will",
  "we'll've": "we will have",
  "we're": "we are",
  "we've": "we have",
  "weren't": "were not",
  "what'll": "what will",
  "what'll've": "what will have",
  "what're": "what are",
  "what's": "what is",
  "what've": "what have",
  "when's": "when is",
  "when've": "when have",
  "where'd": "where did",
  "where's": "where is",
  "where've": "where have",
  "who'll": "who will",
  "who'll've": "who will have",
  "who's": "who is",
  "who've": "who have",
  "why's": "why is",
  "why've": "why have",
  "will've": "will have",
  "won't": "will not",
  "won't've": "will not have",
  "would've": "would have",
  "wouldn't": "would not",
  "wouldn't've": "would not have",
  "y'all": "you all",
  "y'alls": "you alls",
  "y'all'd": "you all would",
  "y'all'd've": "you all would have",
  "y'all're": "you all are",
  "y'all've": "you all have",
  "you'd": "you had",
  "you'd've": "you would have",
  "you'll": "you you will",
  "you'll've": "you you will have",
  "you're": "you are",
  "you've": "you have"
}; 


const contracted2 = {
    "aint": "am not",
  "arent": "are not",
  "cant": "cannot",
  "cantve": "cannot have",
  "'cause": "because",
  "couldve": "could have",
  "couldnt": "could not",
  "couldntve": "could not have",
  "didnt": "did not",
  "doesnt": "does not",
  "dont": "do not",
  "hadnt": "had not",
  "hadntve": "had not have",
  "hasnt": "has not",
  "havent": "have not",
  "hed": "he would",
  "hedve": "he would have",
  "he'll": "he will",
  "he'll've": "he will have",
  "he's": "he is",
  "how'd": "how did",
  "how'd'y": "how do you",
  "how'll": "how will",
  "how's": "how is",
  "Id": "I would",
  "I'd've": "I would have",
  "Ill": "I will",
  "I'll've": "I will have",
  "Im": "I am",
  "Ive": "I have",
  "isnt": "is not",
  "itd": "it had",
  "it'd've": "it would have",
  "it'll": "it will",
  "it'll've": "it will have",
  "it's": "it is",
  "lets": "let us",
  "ma'am": "madam",
  "mayn't": "may not",
  "mightve": "might have",
  "mightnt": "might not",
  "mightn't've": "might not have",
  "mustve": "must have",
  "mustnt": "must not",
  "mustn't've": "must not have",
  "neednt": "need not",
  "needn't've": "need not have",
  "oclock": "of the clock",
  "oughtnt": "ought not",
  "oughtn't've": "ought not have",
  "shant": "shall not",
  "shant": "shall not",
  "shan't've": "shall not have",
  "shed": "she would",
  "she'dve": "she would have",
  "she'll": "she will",
  "she'll've": "she will have",
  "shes": "she is",
  "should've": "should have",
  "shouldnt": "should not",
  "shouldnt've": "should not have",
  "so've": "so have",
  "so's": "so is",
  "thatd": "that would",
  "that'd've": "that would have",
  "thats": "that is",
  "thered": "there had",
  "there'd've": "there would have",
  "theres": "there is",
  "theyd": "they would",
  "they'd've": "they would have",
  "theyll": "they will",
  "they'll've": "they will have",
  "theyre": "they are",
  "theyve": "they have",
  "to've": "to have",
  "wasnt": "was not",
  "wed": "we had",
  "wed've": "we would have",
  "we'll": "we will",
  "we'll've": "we will have",
  "we're": "we are",
  "we've": "we have",
  "werent": "were not",
  "whatll": "what will",
  "what'll've": "what will have",
  "whatre": "what are",
  "whats": "what is",
  "whatve": "what have",
  "whens": "when is",
  "whenve": "when have",
  "whered": "where did",
  "wheres": "where is",
  "where've": "where have",
  "wholl": "who will",
  "who'll've": "who will have",
  "whos": "who is",
  "who've": "who have",
  "whys": "why is",
  "whyve": "why have",
  "willve": "will have",
  "wont": "will not",
  "wont've": "will not have",
  "wouldve": "would have",
  "wouldnt": "would not",
  "wouldnt've": "would not have",
  "yall": "you all",
  "y'lls": "you alls",
  "yall'd": "you all would",
  "yalld've": "you all would have",
  "yall're": "you all are",
  "yall've": "you all have",
  "youd": "you had",
  "youd've": "you would have",
  "youll": "you you will",
  "youll've": "you you will have",
  "youre": "you are",
  "youve": "you have"
}; 


const emoticons = {
    happy: [":‑)",
        ":)", ":-]",
        ":]", ":-3",
        ":3", ":->",
        ":>", "8-)",
        "8)", ":-}",
        ":}", ":o)", 
        ":c)", ":^)",	
        "=]", "=)"], 

    laughing: [
        ":‑D",
        ":D", "8‑D",
        "8D", "x‑D",
        "xD", "X‑D",
        "XD",  "=D",	
        "=3", "B^D"], 

    sad: [
             ":‑(",
            ":(", ":‑c",
            ":c", ":‑<",
            ":<", ":‑[",
            ":[", ":-||", 	
            ":{", ":@"], 
    
    anger: [
        ">:[", ">:(", 
        "D:<", ">:O", 
        ">:O", ">:P"
    ], 

    dismay: [
        "D‑':", "D:<", 
        "D:", "D8", 	
        "D;", "D=", 	
        "DX"], 

    surprise: [
        ":‑O", ":O",	
        ":‑o", ":o", 	
        ":-0", "8‑0",	
    ], 

    disappointed: [
        ":‑/", ":/",	
        "=/", "=L", 
        ":L", ":S"
    ], 

    playful: [
        ":‑P",
        ":P", "X‑P",
        "XP", "x‑p",
        "xp", ":‑p",
        ":p", ":‑Þ",
        ":Þ", ":‑þ",
        ":þ", ":‑b",
        ":b", "d:",	
        "=p", 	
    ], 

    embarrassed: [
        ":$", "://)",
        "://3"
    ], 

    shock: [
        "O_O", "o‑o",	
        "O_o", "o_O",	
        "o_o"
    ],
};






/**
 * Lists here contain conversion for contractions and emojis for use during the vector cleaning process. 
 * Each list is object that is used to convert eiter the text emoji to its associated word or to convert a contraction to its uncontracted form.
 * */  

module.exports.contracted = contracted; 
module.exports.contracted2 = contracted2; 
module.exports.emoticons = emoticons; 